name = "link-collector-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "link-collector-db"
database_id = "link-collector-db"
preview_database_id = "link-collector-db"