name = "stashtab-worker"
main = "src/index.ts"
compatibility_date = "2026-06-23"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[[kv_namespaces]]
binding = "OG_CACHE"
id = "7c13cd17d84c40a5b0985913c410aab3"

[[kv_namespaces]]
binding = "AI_CACHE"
id = "15e5bee51c2b481b8dd8a8f583c6bd4e"
